name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    env:
      SERVER: test.pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build

      - name: Build distributions
        run: |
          rm -rf dist
          python -m build --sdist --wheel --outdir dist

      - name: Publish package distributions to PyPI
        if: ${{ env.SERVER == 'pypi' }}
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package distributions to TestPyPI
        if: ${{ env.SERVER == 'test.pypi' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          verbose: true
